### PR TITLE
Fixes hardcoding the MYSQL version number

### PR DESCRIPTION
**Pull request by kusuriya**

### CODE REVIEW

**Comment by TravisEz13** [comment]
Thanks, for your contribution.
Per the contribution guidelines, [All DSC modules in the DscResources should have tests written using Pester included in a Tests folder.](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#improving-test-coverage-for-existing-resources)
Please include tests for the Get-MySqlProductName and Get-MySqlCatalogName functions minimally.  In general, you should try to cover the code you changed, since there aren't existing tests.

**Comment by NarineM** [comment]
Hi @kusuriya ,
Thanks for your contribution. This is a reminder to add some basic unit tests for your change so that we are able to proceed with the merge request. 

Thanks,
-Narine

**Comment by kusuriya** [comment]
I actually have a few unit tests on deck to add to this, but I need to stir up some for the rest of the module, I am aiming to have it done in the next few weeks, barring any sort of issues.

**Comment by kusuriya** [comment]
Looks like if you merge #8 it beats me to the punch, adds unit tests, and includes my changes. I would suggest merging that PR instead.

**Comment by NarineM** [comment]
Hi @kusuriya,
Yes, I am currently reviewing #8 which covers the fix for your request so this change would no longer be needed to be reviewed.

**Pull request closed without merging**
